version: '2'

volumes:
  postgres:

services:
  postgres:
    image: postgres:9.6
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: flipper
      POSTGRES_USER: flipper
      POSTGRES_PASSWORD: flipper123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5555:5432
